# Generated by Django 4.1.1 on 2022-09-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=1000, verbose_name='title')),
                ('authors', models.CharField(max_length=1000, verbose_name='authors')),
                ('average_rating', models.FloatField()),
                ('isbn', models.IntegerField()),
                ('isbn13', models.IntegerField()),
                ('language_code', models.CharField(max_length=1000, verbose_name='language_code')),
                ('num_pages', models.IntegerField()),
                ('ratings_count', models.IntegerField()),
                ('text_reviews_count', models.IntegerField()),
                ('publisher', models.CharField(max_length=1000, verbose_name='publisher')),
            ],
        ),
    ]
