# Generated by Django 4.1.1 on 2022-09-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_book_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.CharField(max_length=100, verbose_name='isbn13'),
        ),
    ]
