# Generated by Django 4.1.1 on 2022-09-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_book_isbn13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=100, verbose_name='isbn'),
        ),
    ]
