# Generated by Django 4.1.1 on 2022-09-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.CharField(max_length=1000, verbose_name='average_rating'),
        ),
    ]
