# Generated by Django 4.1.1 on 2022-09-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_book_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='num_pages',
            field=models.CharField(max_length=1000, verbose_name='num_pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_count',
            field=models.CharField(max_length=1000, verbose_name='ratings_count'),
        ),
        migrations.AlterField(
            model_name='book',
            name='text_reviews_count',
            field=models.CharField(max_length=1000, verbose_name='text_reviews_count'),
        ),
    ]
