# Generated by Django 4.1.1 on 2022-10-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'attribute',
                'verbose_name_plural': 'attributes',
                'db_table': 'attribute',
            },
        ),
    ]
