# Generated by Django 4.1.1 on 2022-10-02 17:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attribute_value', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField()),
                ('is_default', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('attribute_value', models.ManyToManyField(to='attribute_value.attributevalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
            options={
                'verbose_name': 'inventory',
                'verbose_name_plural': 'inventorys',
                'db_table': 'inventory',
            },
        ),
    ]
